Algoritmo "Media Simples"
//  
// Descrição : Faça a média simples entre 3 notas
// Data atual  : 27/06/2023

Var
// Seção de Declarações das variáveis 
nota1, nota2, nota3, soma, media: real

Inicio
escreva("Digite o primeiro valor: ")
leia(nota1)

escreva("Digite o segundo valor: ")
leia(nota2)

escreva("Digite o terceiro valor: ")
leia(nota3)

soma <- nota1 + nota2 + nota3
media <- soma/3

Escreva("A sua média final é: ",media)

Fimalgoritmo