/*Estrutura de repetição: Enquanto
Algoritimo - Contador: contar de 1 a 10 
*/ 

inicio 

/*inteiro numero 
 
numero <- 1 

enquanto numero < 11 faz 
    Escrever numero, "\t"
    numero <- numero +1  
    
fimenquanto 
*/

/*real numero 
para numero de 1 ate 10 passo 1
     escrever numero, "\t" 
próximo 
*/ 

inteiro mes  

repete 
    escrever "Introduza um mês: " 
    ler mes  
ate mes > 0 e mes < 13 
escrever "\n Mês introduzido: ", mes



fim 
