Algoritmo "semnome"

// Data atual  : 27/06/2023
Var
// Seção de Declarações das variáveis 
valor1, valor2: inteiro
resultado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o primeiro valor: ")
leia(valor1)

escreva("Digite o segundo valor: ")
leia(valor2)

resultado <- valor1 - valor2

escreva("O resultado da operação ", valor1, " - " , valor2, " igual a ", resultado)


Fimalgoritmo