Algoritmo "VerificarParOuImpar"
//  
//  
// Descrição   : Verificar se um numero é par ou impar
// Data atual  : 30/06/2023
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreva("Digite um numero inteiro:")
leia(numero)

Se numero % 2 = 0 Então
   Escreva("O numero é par!")

Senão
  Escreva("O numero é impar!")

FimSe
Fimalgoritmo