Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

// Data atual  : 26/06/2023
Var
// Seção de Declarações das variáveis 
numero1, numero2: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o primeiro numero:")
leia(numero1)

escreva("Digite o segundo numero:")
leia(numero2)

escreval("O primeiro numero é:", numero1)
escreva("O segundo numero é:", numero2)

Fimalgoritmo